name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests=2.28.*
  - pip=23.*
  - mlflow=1.32.*
  - protobuf=3.20.*
  - hydra-core=1.1.*
  - numpy=1.23.*
  - pip:
      - wandb==0.17.2
      - hydra-joblib-launcher==1.1.2