name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.2.1
  - pip=23.3.1
  - pyarrow=14.0.2
  - pytest=8.0.2
  - scipy=1.12.0
  - pip:
      - wandb==0.17.2